name: Build Lyre kernel

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  lyre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential meson nasm linux-libc-dev -y

      - name: Clone mlibc
        run: git clone https://github.com/managarm/mlibc.git

      - name: Checkout and patch mlibc
        run: |
          cd mlibc
          git checkout `grep 'version=' < ../source-recipes/mlibc | sed 's/version=//g'`
          for f in ../patches/mlibc/*; do patch -p1 < $f; done

      - name: Install mlibc headers
        run: |
          mkdir mlibc-build
          cd mlibc-build
          meson setup --cross-file ../build-support/cross_file.txt --prefix=/ -Dheaders_only=true -Dlinux_kernel_headers=/usr/include ../mlibc
          ninja
          mkdir ../mlibc-headers
          DESTDIR=`realpath ../mlibc-headers` ninja install

      - name: Attempt to build the Lyre kernel (debug)
        run: |
          cd kernel
          ./bootstrap
          ./configure --enable-werror CROSS_CPPFLAGS="-nostdinc -I`realpath ../mlibc-headers/include`"
          make PROD=false
          make maintainer-clean

      - name: Attempt to build the Lyre kernel (prod)
        run: |
          cd kernel
          ./bootstrap
          ./configure --enable-werror CROSS_CPPFLAGS="-nostdinc -I`realpath ../mlibc-headers/include`"
          make PROD=true
          make maintainer-clean
