name: Nightly Lyre rebuild

on: ['push']
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  lyre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install make curl git mercurial libarchive-tools xorriso -y

      - name: Build distro
        run: make distro-full

      - name: Build ISO
        run: make all

      - name: Set TAG_DATE variable
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Tag new nightly release
        run: git tag nightly-$TAG_DATE && git push --tags

      - name: Rename lyre.iso
        run: mv lyre.iso lyre-nightly-$(date +'%Y%m%d').iso

      - name: Create nightly release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly build ${{ env.TAG_DATE }}
          tag_name: nightly-${{ env.TAG_DATE }}
          body: Image of an up to date Lyre nightly build.
          files: |
            lyre-nightly-*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
